import { Injectable, NotFoundException } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { PrismaService } from '../../prisma/prisma.service';
import { serializeBigInts, toBigIntId } from '../shared/serialize';
import { CreateDetallePedidoDto, CreateFacturaDto, CreatePedidoDto, UpdateDetallePedidoDto, UpdateFacturaDto, UpdatePedidoDto } from './dto/pedidos.dto';

@Injectable()
export class PedidosService {
  constructor(private readonly prisma: PrismaService) {}
  async findAll() { return serializeBigInts(await this.prisma.pedidos.findMany({ include: { detalle_pedido: true, facturas: true, usuarios: true, monedas: true } })); }
  async findOne(id: string) { const item = await this.prisma.pedidos.findUnique({ where: { id_pedido: toBigIntId(id) }, include: { detalle_pedido: true, facturas: true, usuarios: true, monedas: true } }); if (!item || item.eliminado_en) throw new NotFoundException('Pedido no encontrado'); return serializeBigInts(item); }
  async create(dto: CreatePedidoDto) { return serializeBigInts(await this.prisma.pedidos.create({ data: { id_usuario: dto.id_usuario, estado: dto.estado?.trim() ?? 'pendiente', total: dto.total, moneda: dto.moneda, tipo_cambio: dto.tipo_cambio ?? undefined, moneda_referencia: dto.moneda_referencia?.trim() ?? 'USD', pais_destino_iso2: dto.pais_destino_iso2 ?? undefined, direccion_envio_snapshot: dto.direccion_envio_snapshot as Prisma.InputJsonValue | undefined, direccion_facturacion_snapshot: dto.direccion_facturacion_snapshot as Prisma.InputJsonValue | undefined, devolucion_estado: dto.devolucion_estado ?? undefined, devolucion_motivo: dto.devolucion_motivo ?? undefined } })); }
  async update(id: string, dto: UpdatePedidoDto) { return serializeBigInts(await this.prisma.pedidos.update({ where: { id_pedido: toBigIntId(id) }, data: { id_usuario: dto.id_usuario, estado: dto.estado?.trim(), total: dto.total, moneda: dto.moneda, tipo_cambio: dto.tipo_cambio, moneda_referencia: dto.moneda_referencia?.trim(), pais_destino_iso2: dto.pais_destino_iso2, direccion_envio_snapshot: dto.direccion_envio_snapshot as Prisma.InputJsonValue | undefined, direccion_facturacion_snapshot: dto.direccion_facturacion_snapshot as Prisma.InputJsonValue | undefined, devolucion_estado: dto.devolucion_estado, devolucion_motivo: dto.devolucion_motivo } })); }
  async remove(id: string) { return serializeBigInts(await this.prisma.pedidos.update({ where: { id_pedido: toBigIntId(id) }, data: { eliminado_en: new Date() } })); }
  async addDetalle(id: string, dto: CreateDetallePedidoDto) { return serializeBigInts(await this.prisma.detalle_pedido.create({ data: { id_pedido: toBigIntId(id), id_producto: dto.id_producto, cantidad: dto.cantidad, precio_compra: dto.precio_compra, moneda_compra: dto.moneda_compra?.trim() ?? 'MXN', impuesto: dto.impuesto ?? '0' } })); }
  async updateDetalle(id_detalle: string, dto: UpdateDetallePedidoDto) { return serializeBigInts(await this.prisma.detalle_pedido.update({ where: { id_detalle: toBigIntId(id_detalle) }, data: { id_producto: dto.id_producto, cantidad: dto.cantidad, precio_compra: dto.precio_compra, moneda_compra: dto.moneda_compra?.trim(), impuesto: dto.impuesto } })); }
  async removeDetalle(id_detalle: string) { await this.prisma.detalle_pedido.delete({ where: { id_detalle: toBigIntId(id_detalle) } }); return { message: 'Detalle eliminado' }; }
  async addFactura(id: string, dto: CreateFacturaDto) { return serializeBigInts(await this.prisma.facturas.create({ data: { id_pedido: toBigIntId(id), uuid_fiscal: dto.uuid_fiscal ?? null, pdf_url: dto.pdf_url ?? null, xml_url: dto.xml_url ?? null, rfc_emisor: dto.rfc_emisor ?? null, rfc_receptor: dto.rfc_receptor ?? null, uso_cfdi: dto.uso_cfdi ?? null, regimen_fiscal: dto.regimen_fiscal ?? null, subtotal: dto.subtotal ?? null, impuestos_total: dto.impuestos_total ?? null, total: dto.total ?? null, moneda: dto.moneda ?? null, estado: dto.estado?.trim() ?? 'pendiente' } })); }
  async updateFactura(id_factura: string, dto: UpdateFacturaDto) { return serializeBigInts(await this.prisma.facturas.update({ where: { id_factura: toBigIntId(id_factura) }, data: { uuid_fiscal: dto.uuid_fiscal, pdf_url: dto.pdf_url, xml_url: dto.xml_url, rfc_emisor: dto.rfc_emisor, rfc_receptor: dto.rfc_receptor, uso_cfdi: dto.uso_cfdi, regimen_fiscal: dto.regimen_fiscal, subtotal: dto.subtotal, impuestos_total: dto.impuestos_total, total: dto.total, moneda: dto.moneda, estado: dto.estado } })); }
  async removeFactura(id_factura: string) { await this.prisma.facturas.delete({ where: { id_factura: toBigIntId(id_factura) } }); return { message: 'Factura eliminada' }; }
}
